Callori/Callori/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Callori/main/urls.py
from django.urls import path
from .views import index, other_page, BBLogin_View, profile, BBLogout_View, ProfileEditView, PasswordEditView, RegisterView, RegisterDoneView, user_activate, ProfileDeleteView, blog, posted_detail, profile_posted_add


app_name = 'main'
urlpatterns = [
 path('accounts/profile/add/', profile_posted_add, name='profile_bb_add'),
 path('accounts/profile/<int:pk>/', posted_detail, name='profile_bb_detail'),
 path('<int:pk>/', posted_detail, name='posted_detail'),
 path('<str:page>/', other_page, name='other'),
 path('', index, name='index'),
 path('accounts/login/', BBLogin_View.as_view(), name='login'),
 path('accounts/profile/', profile, name='profile'),
 path('accounts/logout/', BBLogout_View.as_view(), name='logout'),
 path('accounts/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
 path('accounts/password/edit/', PasswordEditView.as_view(), name='password_edit'),
 path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
 path('accounts/register/', RegisterView.as_view(), name='register'),
 path('accounts/activate/<str:sign>/', user_activate, name='activate'),
 path('accounts/profile/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
 path('blog/', blog, name='blog'),
]

Callori/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path

class User(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Вы прошли активацию?")
    send_message = models.BooleanField(default=True, verbose_name="Присылать вам оповещения о комментариях?")

    def delete(self, *args, **kwargs):
        for bb in self.posted_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass


class Posted(models.Model):
    title = models.CharField(max_length=40, verbose_name='Название поста')
    content = models.TextField(verbose_name='Описание')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор объявления')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
            super().delete(*args, **kwargs)
    class Meta:
        verbose_name_plural = 'Пост'
        verbose_name = 'Посты'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Posted, on_delete=models.CASCADE, verbose_name='Пост')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')
    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

Callori/main/forms.py
from django import forms
from .models import User, Posted, AdditionalImage
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .signals import post_register

# Изменение данных пользователя кроме пароля
class ProfileEditForm(forms.ModelForm):
    username = forms.CharField(required=True, label='Ваше пользовательское имя')
    email = forms.EmailField(required=True, label='Адрес электроннной почты')
    first_name = forms.CharField(required=True, label='Ваше Имя')
    last_name = forms.CharField(required=True, label='Ваша Фамилия')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'send_message')

# Регистрируем новых пользователей
class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput, help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
            'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
            post_register.send(RegisterForm, instance=user)
            return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_message')



class PostedForm(forms.ModelForm):
    class Meta:
        model = Posted
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


AIFormSet = forms.inlineformset_factory(Posted, AdditionalImage, fields='__all__')

Callori/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template.loader import get_template
from django.template import TemplateDoesNotExist
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import User, Posted
from .forms import ProfileEditForm, AIFormSet, PostedForm
from django.views.generic.edit import CreateView
from .forms import RegisterForm
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from .utilities import signer
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect

# Вход на главную страницу
def index(request):
    bbs = Posted.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)
# Открытие других страниц
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))
# Регистрация
class BBLogin_View(LoginView):
    template_name = 'main/login.html'

# Выход
class BBLogout_View(LogoutView):
    pass
# Профиль
@login_required()
def profile(request):
    bbs = Posted.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)
# Изменения дааных пользователя кроме пароля
class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'main/profile_edit.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
            return get_object_or_404(queryset, pk=self.user_id)
# Изменение пароля
class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_edit.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'
# Страница Регистрации
class RegisterView(CreateView):
    model = User
    template_name = 'main/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('main:register_done')

# Страница об успешной авторизации
class RegisterDoneView(TemplateView):
 template_name = 'main/register_done.html'

# Активация нового пользователя
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/activation_failed.html')
    user = get_object_or_404(User, username=username)
    if user.is_activated:
        template = 'main/activation_done_earlier.html'
    else:
        template = 'main/activation_done.html'
    user.is_active = True
    user.is_activated = True
    user.save()
    return render(request, template)

# Удаление пользователя
class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/profile_delete.html'
    success_url = reverse_lazy('main:index')
    success_message = 'Пользователь удален'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

def blog(request):
    bbs = Posted.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/blog.html', context)

def posted_detail(request, pk):
    return render(request, 'main/posted_detail.html', context={'bb': get_object_or_404(Posted, pk=pk)})

@login_required
def profile_posted_add(request):
    if request.method == 'POST':
        form = PostedForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS,'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = PostedForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_posted_set.html', context)

Callori/main/templates/main/about.html
{% extends 'layout/basic.html' %}
{% block title %}Про нас{% endblock %}
{% block content %}
<h2>Что-то типа про нас</h2>
{% endblock %}

Callori/main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}
{% block title %}Активация выполнена{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

Callori/main/templates/main/activation_done_earlier.html
{% extends 'layout/basic.html' %}
{% block title %}Пользователь уже активирован{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

Callori/main/templates/main/activation_failed.html
{% extends 'layout/basic.html' %}
{% block title %}Ошибка при активации{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

Callori/main/templates/main/blog.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}блог{% endblock %}
{% block content %}
<h2 class="mb-2">Блог</h2>
{% if bbs %}
<div class="vstack gap-3 my-4">
 {% for bb in bbs %}
 <div class="card">
 {% url 'main:bb_detail' pk=bb.pk as url %}
 <div class="row p-3">
 <a class="col-md-2" href="{{ url }}{{ all }}">
 {% if bb.image %}
 <img class="img-fluid"
 src="{% thumbnail bb.image 'default' %}">
 {% else %}
 <img class="img-fluid" src="{% static 'main/empty.jpg' %}">
 {% endif %}
 </a>
 <div class="col-md-10 card-body">
 <h3 class="card-title"><a href="{{ url }}{{ all }}">
 {{ bb.title }}</a></h3>
 <div class="card-text mb-2">{{ bb.content }}</div>
 <p class="card-text text-end fst-italic">{{ bb.created_at }}</p>
 </div>
 </div>
 </div>
 {% endfor %}
</div>
{% endif %}
{% endblock %}

Callori/main/templates/main/delete.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Удаление пользователя{% endblock %}
{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
 {% csrf_token %}
 {% bootstrap_button 'Удалить' button_class='btn-danger' %}
</form>
{% endblock %}

Callori/main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}блог{% endblock %}
{% block content %}
<h2 class="mb-2">Блог</h2>
{% if bbs %}
<div class="vstack gap-3 my-4"
     {% for bb in bbs %}
     <div class="card">
      {% url 'main:posted_detail' pk=bb.pk as url %}
         <div class="row p-3">
          <a class="col-md-2" href="{{ url }}{{ all }}">
           {% if bb.image %}
               <img class="img-fluid" src="{% thumbnail bb.image 'default' %}">
           {% else %}
               <img class="img-fluid" src="{% static 'main/empty.jpg' %}">
           {% endif %}
          </a>
       <div class="col-md-10 card-body">
           <h3 class="card-title"><a href="{{ url }}{{ all }}">
            { bb.title }}</a></h3>
        <div class="card-text mb-2">{{ bb.content }}</div>
        <p class="card-text text-end fst-italic">{{ bb.created_at }}</p>
       </div>
      </div>
 </div>
 {% endfor %}
</div>
{% endif %}
{% endblock %} %}

Callori/main/templates/main/login.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Вход{% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
 {% csrf_token %}
 {% bootstrap_form form layout='horizontal' %}
 <input type="hidden" name="next" value="{{ next }}">
 {% bootstrap_button 'Войти' %}
</form>
{% endif %}
{% endblock %}

Callori/main/templates/main/password_edit.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
 {% csrf_token %}
 {% bootstrap_form form layout='horizontal' %}
 {% bootstrap_button 'Сменить пароль' %}
</form>
{% endblock %}

Callori/main/templates/main/posted_detail.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}{{ bb.title }}{% endblock %}
{% block content %}
<div class="row mt-3">
 {% if bb.image %}
 <div class="col-md-auto">
 <img src="{{ bb.image.url }}" class="main-image">
 </div>
 {% endif %}
 <div class="col">
 <h2>{{ bb.title }}</h2>
 <p bg-light>{{ bb.content }}</p>
 <p>{{ bb.contacts }}</p>
 <p class="text-end fst-italic">Добавлено {{ bb.created_at }}</p>
 </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
 {% for ai in ais %}
 <div class="d-flex justify-content-center align-items-center">
 <img class="additional-image" src="{{ ai.image.url }}">
 </div>
 {% endfor %}
</div>
{% endif %}
<form class="px-3" method="post" action="{% url 'main:blog' %}">
                                    {% csrf_token %}
                                    {% bootstrap_button 'Выйти' button_class='btn-danger' %}
 </form>
{% endblock %}

Callori/main/templates/main/profile.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}Профиль пользователя{% endblock %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'main:profile_bb_add' %}">Добавить объявление</a></p>
<h3>Ваши объявления</h3>
{% if bbs %}
<div class="vstack gap-3 my-4">
 {% for bb in bbs %}
 <div class="card">
 {% url 'main:profile_bb_detail' pk=bb.pk as url %}
 <div class="row p-3">
 <a class="col-md-2" href="{{ url }}{{ all }}">
 {% if bb.image %}
 <img class="img-fluid"
 src="{% thumbnail bb.image 'default' %}">
 {% else %}
 <img class="img-fluid" src="{% static 'main/empty.jpg' %}">
 {% endif %}
 </a>
 <div class="col-md-10 card-body">
 <h3 class="card-title"><a href="{{ url }}{{ all }}">
 {{ bb.title }}</a></h3>
 <div class="card-text mb-2">{{ bb.content }}</div>
 <p class="card-text text-end fst-italic">
 {{ bb.created_at }}</p>
 </div>
     </div>
 </div>
 {% endfor %}
</div>
{% endif %}
{% endblock %}

Callori/main/templates/main/profile_edit.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Правка личных данных{% endblock %}
{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
 {% csrf_token %}
 {% bootstrap_form form layout='horizontal' %}
 {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

Callori/main/templates/main/profile_posted_set.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Добавление объявления - Профиль пользователя{% endblock %}
{% block content %}
<h2>Добавление объявления</h2>
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}
 {% bootstrap_form form layout='horizontal' %}
 {% bootstrap_formset formset layout='horizontal' %}
 {% bootstrap_button 'Добавить' %}
</form>
{% endblock %}

Callori/main/templates/main/register_done.html
{% extends 'layout/basic.html' %}
{% block title %}Регистрация завершена{% endblock %}
{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо
 для активации.</p>
{% endblock %}