Callori/Callori/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Callori/main/urls.py
from django.urls import path
from .views import index, other_page, BBLogin_View, profile, BBLogout_View, ProfileEditView, PasswordEditView, RegisterView, RegisterDoneView, user_activate, ProfileDeleteView, blog, posted_detail, profile_posted_add


app_name = 'main'
urlpatterns = [
 path('accounts/profile/add/', profile_posted_add, name='profile_bb_add'),
 path('accounts/profile/<int:pk>/', posted_detail, name='profile_bb_detail'),
 path('<int:pk>/', posted_detail, name='posted_detail'),
 path('<str:page>/', other_page, name='other'),
 path('', index, name='index'),
 path('accounts/login/', BBLogin_View.as_view(), name='login'),
 path('accounts/profile/', profile, name='profile'),
 path('accounts/logout/', BBLogout_View.as_view(), name='logout'),
 path('accounts/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
 path('accounts/password/edit/', PasswordEditView.as_view(), name='password_edit'),
 path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
 path('accounts/register/', RegisterView.as_view(), name='register'),
 path('accounts/activate/<str:sign>/', user_activate, name='activate'),
 path('accounts/profile/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
 path('blog/', blog, name='blog'),
]

Callori/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path

class User(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Вы прошли активацию?")
    send_message = models.BooleanField(default=True, verbose_name="Присылать вам оповещения о комментариях?")

    def delete(self, *args, **kwargs):
        for bb in self.posted_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass


class Posted(models.Model):
    title = models.CharField(max_length=40, verbose_name='Название поста')
    content = models.TextField(verbose_name='Описание')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор объявления')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
            super().delete(*args, **kwargs)
    class Meta:
        verbose_name_plural = 'Пост'
        verbose_name = 'Посты'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Posted, on_delete=models.CASCADE, verbose_name='Пост')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')
    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

Callori/main/forms.py
from django import forms
from .models import User, Posted, AdditionalImage
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .signals import post_register

# Изменение данных пользователя кроме пароля
class ProfileEditForm(forms.ModelForm):
    username = forms.CharField(required=True, label='Ваше пользовательское имя')
    email = forms.EmailField(required=True, label='Адрес электроннной почты')
    first_name = forms.CharField(required=True, label='Ваше Имя')
    last_name = forms.CharField(required=True, label='Ваша Фамилия')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'send_message')

# Регистрируем новых пользователей
class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput, help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
            'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
            post_register.send(RegisterForm, instance=user)
            return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_message')



class PostedForm(forms.ModelForm):
    class Meta:
        model = Posted
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


AIFormSet = forms.inlineformset_factory(Posted, AdditionalImage, fields='__all__')

Callori/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template.loader import get_template
from django.template import TemplateDoesNotExist
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import User, Posted
from .forms import ProfileEditForm, AIFormSet, PostedForm
from django.views.generic.edit import CreateView
from .forms import RegisterForm
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from .utilities import signer
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect

# Вход на главную страницу
def index(request):
    bbs = Posted.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)
# Открытие других страниц
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))
# Регистрация
class BBLogin_View(LoginView):
    template_name = 'main/login.html'

# Выход
class BBLogout_View(LogoutView):
    pass
# Профиль
@login_required()
def profile(request):
    bbs = Posted.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)
# Изменения дааных пользователя кроме пароля
class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'main/profile_edit.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
            return get_object_or_404(queryset, pk=self.user_id)
# Изменение пароля
class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_edit.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'
# Страница Регистрации
class RegisterView(CreateView):
    model = User
    template_name = 'main/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('main:register_done')

# Страница об успешной авторизации
class RegisterDoneView(TemplateView):
 template_name = 'main/register_done.html'

# Активация нового пользователя
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/activation_failed.html')
    user = get_object_or_404(User, username=username)
    if user.is_activated:
        template = 'main/activation_done_earlier.html'
    else:
        template = 'main/activation_done.html'
    user.is_active = True
    user.is_activated = True
    user.save()
    return render(request, template)

# Удаление пользователя
class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/profile_delete.html'
    success_url = reverse_lazy('main:index')
    success_message = 'Пользователь удален'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

def blog(request):
    bbs = Posted.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/blog.html', context)

def posted_detail(request, pk):
    return render(request, 'main/posted_detail.html', context={'bb': get_object_or_404(Posted, pk=pk)})

@login_required
def profile_posted_add(request):
    if request.method == 'POST':
        form = PostedForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS,'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = PostedForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_posted_set.html', context)

Callori/main/templates/layout/basic.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Блог</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
         {% bootstrap_javascript %}
    </head>

    <body class="container-fluid">
        <header class="bg-success">
            <h1 class="display-1 text-center">Callori</h1>
        </header>
        <nav class="row navbar navbar-expand-md bg-success">
            <div class="col container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'main:profile' %}">Профиль</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'main:profile' %}">Мои посты</a>
                                <a class="dropdown-item" href="{% url 'main:profile_edit' %}">Изменить личные данные</a>
                                <a class="dropdown-item" href="{% url 'main:password_edit' %}">Изменить пароль</a>
                                <hr class="dropdown-divider">
                                <form class="px-3" method="post" action="{% url 'main:logout' %}">
                                    {% csrf_token %}
                                    {% bootstrap_button 'Выйти' button_class='btn-danger' %}
                                </form>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
                            </div>
                        </div>
                        {% else %}
                        <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                        <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <div class="row">
            <nav class="col-md-auto nav flex-column bg-light">
                <ul>
                    <span class="nav-link root"><p>Мои каллории</p></span>
                    <a class="nav-link" href="#"><li>Спорт</li></a>
                    <a class="nav-link" href="#"><li>Еда</li></a>
                    <a class="nav-link" href="#"><li>Мой прогресс</li></a>
                    <span class="nav-link root" ><p>Блог</p></span>
                    <a class="nav-link" href="{% url 'main:blog' %}"><li>Новые посты</li></a>
                    <a class="nav-link" href="#"><li>Чаты и сообщества</li></a>
                    <a class="nav-link root" href="{% url 'main:other' page='about' %}"><li>О сайте</li></a>
                </ul>
            </nav>
            <main class="col py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </main>
        </div>
        <footer class="mt-3">
            <p class="text-end fst-italic">&copy; читатели.</p>
        </footer>
    </body>
</html>